package dev.biserman.planet.planet.ecology

/** Named ecological traits; every constant declares its complete effect bundle here. */
enum class Trait(
    /** Effects contributed by the enum constant. */
    vararg effectList: TraitEffect,
) : SpeciesTrait {
    SESSILE_PRODUCER(
        GrantsTag(EffectTag.AUTOTROPHY),
        GrantsTag(EffectTag.SESSILE),
        ConflictsWithTag(EffectTag.MOTILE),
    ),
    PHOTOSYNTHETIC(
        GrantsTag(EffectTag.AUTOTROPHY),
        MaintenanceCost(0.015),
        NumericMultiplier(NumericTarget.AUTOTROPHY_GROWTH_RATE, 0.30),
        NumericMultiplier(NumericTarget.CARRYING_CAPACITY, 0.35),
    ),
    GRASS_LIKE(
        MaintenanceCost(0.002),
        NumericOffset(NumericTarget.CARRYING_CAPACITY, 0.45),
    ),
    LEAFY(
        MaintenanceCost(0.003),
        NumericOffset(NumericTarget.CARRYING_CAPACITY, 0.25),
    ),
    LOW_FOLIAGE(
        RequiresTag(EffectTag.AUTOTROPHY),
        EdibleAs(FoodResource.LOW_FOLIAGE),
    ),
    CANOPY_FOLIAGE(
        RequiresTag(EffectTag.AUTOTROPHY),
        EdibleAs(FoodResource.CANOPY_FOLIAGE),
        MaintenanceCost(0.003),
    ),
    LARGE_CANOPY(
        RequiresTag(EffectTag.SESSILE),
        CanopyEffect(maximumLightInterception = 0.95),
        MaintenanceCost(0.012),
        NumericMultiplier(NumericTarget.AUTOTROPHY_GROWTH_RATE, 0.92),
    ),
    COARSE_GRASS(
        RequiresTag(EffectTag.AUTOTROPHY),
        EdibleAs(FoodResource.COARSE_GRASS, preferenceMultiplier = 0.85),
        MaintenanceCost(0.002),
        NumericMultiplier(NumericTarget.AUTOTROPHY_GROWTH_RATE, 0.95),
    ),
    BAMBOO_CULMS(
        RequiresTag(EffectTag.AUTOTROPHY),
        EdibleAs(FoodResource.BAMBOO, preferenceMultiplier = 1.0),
        MaintenanceCost(0.004),
        NumericOffset(NumericTarget.CARRYING_CAPACITY, 0.30),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 1.75),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -4.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, 4.0),
    ),
    RHIZOMATOUS_GROWTH(
        RequiresTag(EffectTag.AUTOTROPHY),
        GrantsTag(EffectTag.WINTER_SURVIVAL),
        MaintenanceCost(0.006),
        NumericMultiplier(NumericTarget.AUTOTROPHY_GROWTH_RATE, 1.15),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -8.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, 2.0),
    ),
    DRIP_TIP_LEAVES(
        RequiresTag(EffectTag.AUTOTROPHY),
        MaintenanceCost(0.004),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 1.50),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, 4.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, 4.0),
        NumericMultiplier(NumericTarget.CLIMATE_STRESS_SENSITIVITY, 0.85),
    ),
    FRUITING(
        EdibleAs(
            FoodResource.FRUIT,
            preyLossFraction = 0.1,
            renewableProductionRate = 0.30,
        ),
        MaintenanceCost(0.015),
    ),
    SEED_BEARING(
        EdibleAs(
            FoodResource.SEED,
            preyLossFraction = 0.05,
            renewableProductionRate = 0.08,
        ),
        MaintenanceCost(0.008),
    ),
    WOODY(
        EdibleAs(FoodResource.WOOD),
        NumericOffset(NumericTarget.CARRYING_CAPACITY, 1.05),
        NumericMultiplier(NumericTarget.AUTOTROPHY_GROWTH_RATE, 0.50),
    ),
    FAST_GROWING(
        NumericMultiplier(NumericTarget.AUTOTROPHY_GROWTH_RATE, 1.70),
        MaintenanceCost(0.020),
        ExclusiveEffect(ExclusiveGroup.GROWTH_SPEED),
    ),
    SLOW_GROWING(
        NumericMultiplier(NumericTarget.AUTOTROPHY_GROWTH_RATE, 0.32),
        ExclusiveEffect(ExclusiveGroup.GROWTH_SPEED),
    ),
    EVERGREEN(
        NumericMultiplier(NumericTarget.SEASONAL_AMPLITUDE, 0.28),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -5.0),
        MaintenanceCost(0.008),
    ),

    GRASS_GRAZER(
        GrantsTag(EffectTag.FEEDING),
        MaintenanceCost(0.004),
        FeedsOn(FoodResource.LOW_FOLIAGE, preference = 0.55),
        FeedsOn(FoodResource.COARSE_GRASS, preference = 0.35),
    ),
    BAMBOO_SPECIALIST(
        GrantsTag(EffectTag.FEEDING),
        MaintenanceCost(0.006),
        FeedsOn(FoodResource.BAMBOO, preference = 1.35),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 1.60),
        NumericMultiplier(NumericTarget.ASSIMILATION_EFFICIENCY, 0.65),
    ),
    LEAF_EATER(
        GrantsTag(EffectTag.FEEDING),
        MaintenanceCost(0.004),
        FeedsOn(FoodResource.LOW_FOLIAGE, preference = 0.55),
        FeedsOn(FoodResource.CANOPY_FOLIAGE, preference = 0.35),
    ),
    GROUND_FORAGING(
        RequiresTag(EffectTag.FEEDING),
        MaintenanceCost(0.004),
        FeedsOn(FoodResource.LOW_FOLIAGE, preference = 1.00),
    ),
    HIGH_BROWSING(
        RequiresTag(EffectTag.FEEDING),
        MaintenanceCost(0.008),
        FeedsOn(FoodResource.CANOPY_FOLIAGE, preference = 1.00),
    ),
    FRUGIVORE(
        GrantsTag(EffectTag.FEEDING),
        MaintenanceCost(0.006),
        FeedsOn(FoodResource.FRUIT, preference = 1.10),
    ),
    SEED_EATER(
        GrantsTag(EffectTag.FEEDING),
        MaintenanceCost(0.004),
        FeedsOn(FoodResource.SEED, preference = 0.75),
    ),
    DENDROVORE(
        GrantsTag(EffectTag.FEEDING),
        MaintenanceCost(0.006),
        FeedsOn(FoodResource.WOOD, preference = 0.70),
    ),
    INSECTIVORE(
        GrantsTag(EffectTag.FEEDING),
        MaintenanceCost(0.006),
        FeedsOn(
            FoodResource.MOTILE_PREY,
            preference = 0.95,
            maximumPreySizeRank = SizeClass.TINY.rank,
        ),
    ),
    FILTER_FEEDER(
        GrantsTag(EffectTag.FEEDING),
        MaintenanceCost(0.008),
        FeedsOn(
            FoodResource.MOTILE_PREY,
            preference = 1.00,
            maximumPreySizeRank = SizeClass.TINY.rank,
        ),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 1.15),
    ),
    BENTHIC_FORAGER(
        GrantsTag(EffectTag.FEEDING),
        MaintenanceCost(0.006),
        FeedsOn(
            FoodResource.MOTILE_PREY,
            preference = 0.90,
            maximumPreySizeRank = SizeClass.SMALL.rank,
        ),
    ),
    CARNIVORE(
        GrantsTag(EffectTag.FEEDING),
        MaintenanceCost(0.008),
        FeedsOn(
            FoodResource.MOTILE_PREY,
            preference = 1.00,
            minimumRelativeSize = -2,
            maximumRelativeSize = 0,
        ),
    ),
    OMNIVORE(
        GrantsTag(EffectTag.FEEDING),
        MaintenanceCost(0.012),
        FeedsOn(
            FoodResource.MOTILE_PREY,
            preference = 0.60,
            minimumRelativeSize = -2,
            maximumRelativeSize = 0,
        ),
        FeedsOn(FoodResource.FRUIT, preference = 0.75),
        FeedsOn(FoodResource.SEED, preference = 0.55),
    ),

    MOTILE(
        GrantsTag(EffectTag.MOTILE),
        MaintenanceCost(0.010),
        EdibleAs(FoodResource.MOTILE_PREY),
    ),
    WARM_BLOODED(
        RequiresTag(EffectTag.MOTILE),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 5.0),
        NumericMultiplier(NumericTarget.METABOLIC_DEMAND_RATE, 5.0),
        NumericMultiplier(NumericTarget.STARVATION_MORTALITY_RATE, 1.50),
        NumericMultiplier(NumericTarget.MORTALITY_RATE, 1.15),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -8.0),
    ),
    PACK_HUNTER(
        GrantsTag(EffectTag.PACK_HUNTING),
        RequiresTag(EffectTag.FEEDING),
        MaintenanceCost(0.012),
        ExclusiveEffect(ExclusiveGroup.HUNTING_STRATEGY),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 1.05),
        NumericMultiplier(NumericTarget.DENSITY_DEPENDENCE, 0.80),
        NumericMultiplier(NumericTarget.INTERFERENCE, 0.58),
        RelativeSizeModifier(maximumRelativeSizeBonus = 1),
    ),
    AMBUSH_PREDATOR(
        GrantsTag(EffectTag.AMBUSH_HUNTING),
        RequiresTag(EffectTag.FEEDING),
        MaintenanceCost(0.005),
        ExclusiveEffect(ExclusiveGroup.HUNTING_STRATEGY),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 0.90),
        NumericMultiplier(NumericTarget.INTERFERENCE, 0.75),
        NumericMultiplier(NumericTarget.RESPONSE_EXPONENT, 1.20),
    ),
    CHASE_PREDATOR(
        GrantsTag(EffectTag.CHASE_HUNTING),
        RequiresTag(EffectTag.FEEDING),
        MaintenanceCost(0.010),
        ExclusiveEffect(ExclusiveGroup.HUNTING_STRATEGY),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 1.15),
        NumericMultiplier(NumericTarget.INTERFERENCE, 1.25),
    ),
    FLIGHT(
        GrantsTag(EffectTag.FLIGHT),
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.045),
        DefenseEffect(
            defaultPreferenceMultiplier = 0.08,
            counterMultipliers = mapOf(
                EffectTag.FLIGHT to 1.0,
                EffectTag.AMBUSH_HUNTING to 0.30,
                EffectTag.AERIAL_PREY_CAPTURE to 0.75,
            ),
        ),
    ),
    BURROWING(
        GrantsTag(EffectTag.BURROWING),
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.020),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -2.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, 2.0),
        NumericUpperBound(NumericTarget.MAX_OPTIMUM_MOISTURE_MM, 140.0),
        DefenseEffect(
            defaultPreferenceMultiplier = 0.30,
            counterMultipliers = mapOf(
                EffectTag.BURROWING to 1.0,
                EffectTag.AMBUSH_HUNTING to 0.65,
            ),
        ),
    ),
    ARMORED(
        MaintenanceCost(0.025),
        DefenseEffect(
            defaultPreferenceMultiplier = 0.35,
            ignoredWhenFeederSizeAdvantageAtLeast = 2,
        ),
    ),
    VENOMOUS(
        MaintenanceCost(0.018),
        DefenseEffect(defaultPreferenceMultiplier = 0.75),
    ),
    NOCTURNAL(
        GrantsTag(EffectTag.NOCTURNAL),
        MaintenanceCost(0.005),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, 3.0),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, 3.0),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_INSOLATION_W_M2, 0.35),
        NumericMultiplier(NumericTarget.MAX_OPTIMUM_INSOLATION_W_M2, 0.70),
        DefenseEffect(
            defaultPreferenceMultiplier = 0.60,
            counterMultipliers = mapOf(EffectTag.NOCTURNAL to 1.0),
        ),
    ),
    REFLECTIVE_RETINA(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.006),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_INSOLATION_W_M2, 0.55),
        NumericMultiplier(NumericTarget.MAX_OPTIMUM_INSOLATION_W_M2, 0.80),
    ),
    LARGE_EYES(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.008),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_INSOLATION_W_M2, 0.70),
        NumericMultiplier(NumericTarget.MAX_OPTIMUM_INSOLATION_W_M2, 0.90),
    ),
    CONSTRICTING_PUPILS(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.005),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_INSOLATION_W_M2, 0.85),
        NumericMultiplier(NumericTarget.MAX_OPTIMUM_INSOLATION_W_M2, 1.40),
    ),
    UV_FILTERING_LENSES(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.004),
        NumericMultiplier(NumericTarget.MAX_OPTIMUM_INSOLATION_W_M2, 1.50),
    ),
    AQUATIC(
        MaintenanceCost(0.012),
        NumericMultiplier(NumericTarget.CARRYING_CAPACITY, 1.10),
        NumericMultiplier(NumericTarget.SEASONAL_AMPLITUDE, 0.67),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 0.0),
    ),
    AMPHIBIOUS(
        MaintenanceCost(0.008),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 1.25),
        HabitatPreferenceEffect(
            axis = HabitatAxis.WETLAND_AVAILABILITY,
            minimum = 0.10,
            mortalityAtExtreme = 0.35,
        ),
        HabitatRefugeEffect(
            axis = HabitatAxis.WETLAND_AVAILABILITY,
            refugeStartsAt = 0.10,
            predatorPreferenceAtFullRefuge = 0.70,
        ),
    ),
    THICK_FUR(
        RequiresTag(EffectTag.MOTILE),
        ExclusiveEffect(ExclusiveGroup.COAT_DENSITY),
        MaintenanceCost(0.008),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -6.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, -2.0),
        HeatRetentionEffect(mortalityPerDegreeAboveThreshold = 0.020),
    ),
    BLUBBER(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.015),
        NumericMultiplier(NumericTarget.STARVATION_MORTALITY_RATE, 0.75),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -8.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, -4.0),
        HeatRetentionEffect(mortalityPerDegreeAboveThreshold = 0.030),
    ),
    SUBCUTANEOUS_FAT(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.014),
        NumericMultiplier(NumericTarget.STARVATION_MORTALITY_RATE, 0.80),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -6.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, -7.0),
        HeatRetentionEffect(mortalityPerDegreeAboveThreshold = 0.035, thresholdC = 16.0),
    ),
    COUNTERCURRENT_HEAT_EXCHANGE(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.012),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -4.0),
    ),
    THICK_BARK(
        RequiresTag(EffectTag.AUTOTROPHY),
        MaintenanceCost(0.006),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -4.0),
    ),
    DORMANT_BUDS(
        RequiresTag(EffectTag.AUTOTROPHY),
        GrantsTag(EffectTag.WINTER_SURVIVAL),
        MaintenanceCost(0.006),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -6.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, -2.0),
    ),
    UNDERGROUND_MERISTEMS(
        RequiresTag(EffectTag.AUTOTROPHY),
        GrantsTag(EffectTag.WINTER_SURVIVAL),
        MaintenanceCost(0.006),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -35.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, -4.0),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 0.55),
        NumericMultiplier(NumericTarget.CLIMATE_STRESS_SENSITIVITY, 0.35),
    ),
    NEEDLE_LEAVES(
        RequiresTag(EffectTag.AUTOTROPHY),
        GrantsTag(EffectTag.WINTER_SURVIVAL),
        MaintenanceCost(0.006),
        NumericMultiplier(NumericTarget.AUTOTROPHY_GROWTH_RATE, 0.80),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -8.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, -2.0),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 0.45),
        NumericMultiplier(NumericTarget.CLIMATE_STRESS_SENSITIVITY, 0.55),
    ),
    PROSTRATE_WOODY_GROWTH(
        RequiresTag(EffectTag.SESSILE),
        MaintenanceCost(0.004),
        NumericMultiplier(NumericTarget.AUTOTROPHY_GROWTH_RATE, 0.70),
        NumericMultiplier(NumericTarget.CARRYING_CAPACITY, 0.45),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -24.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, -6.0),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 0.55),
        NumericMultiplier(NumericTarget.CLIMATE_STRESS_SENSITIVITY, 0.45),
        HeatRetentionEffect(mortalityPerDegreeAboveThreshold = 0.060, thresholdC = 14.0),
    ),
    LARGE_HEAT_RADIATING_EARS(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.005),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, 2.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, 7.0),
        ColdExposureEffect(mortalityPerDegreeBelowFreezing = 0.025),
    ),
    SPARSE_COAT(
        RequiresTag(EffectTag.MOTILE),
        ExclusiveEffect(ExclusiveGroup.COAT_DENSITY),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, 5.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, 5.0),
        ColdExposureEffect(mortalityPerDegreeBelowFreezing = 0.050),
    ),
    ESTIVATION(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.012),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, 6.0),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 0.80),
    ),
    WAXY_CUTICLE(
        RequiresTag(EffectTag.AUTOTROPHY),
        MaintenanceCost(0.008),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 0.70),
    ),
    DEEP_ROOTS(
        RequiresTag(EffectTag.SESSILE),
        MaintenanceCost(0.012),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 0.60),
    ),
    WATER_STORAGE_TISSUE(
        RequiresTag(EffectTag.AUTOTROPHY),
        MaintenanceCost(0.015),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 0.70),
    ),
    CAM_PHOTOSYNTHESIS(
        RequiresTag(EffectTag.AUTOTROPHY),
        MaintenanceCost(0.008),
        NumericMultiplier(NumericTarget.AUTOTROPHY_GROWTH_RATE, 0.55),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 0.25),
        NumericMultiplier(NumericTarget.CLIMATE_STRESS_SENSITIVITY, 0.40),
        NumericUpperBound(NumericTarget.MAX_OPTIMUM_MOISTURE_MM, 80.0),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, 5.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, 10.0),
    ),
    DROUGHT_DECIDUOUS_FOLIAGE(
        RequiresTag(EffectTag.AUTOTROPHY),
        MaintenanceCost(0.004),
        NumericMultiplier(NumericTarget.AUTOTROPHY_GROWTH_RATE, 0.85),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 0.30),
        NumericMultiplier(NumericTarget.CLIMATE_STRESS_SENSITIVITY, 0.35),
        NumericUpperBound(NumericTarget.MAX_OPTIMUM_MOISTURE_MM, 140.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, 6.0),
    ),
    CONCENTRATED_URINE(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.010),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 0.70),
    ),
    WAXY_EXOSKELETON(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.008),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 0.35),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, 2.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, 5.0),
    ),
    ENLARGED_LUNGS(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.014),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 0.96),
        AltitudeToleranceEffect(maximumOptimalAltitudeMeters = 6_000.0, mortalityPerKilometerAbove = 0.22),
    ),
    HIGH_AFFINITY_HEMOGLOBIN(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.010),
        AltitudeToleranceEffect(maximumOptimalAltitudeMeters = 5_200.0, mortalityPerKilometerAbove = 0.25),
    ),
    ALPINE_CUSHION_GROWTH(
        RequiresTag(EffectTag.AUTOTROPHY),
        GrantsTag(EffectTag.WINTER_SURVIVAL),
        MaintenanceCost(0.008),
        NumericMultiplier(NumericTarget.AUTOTROPHY_GROWTH_RATE, 0.72),
        NumericMultiplier(NumericTarget.CARRYING_CAPACITY, 0.60),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -10.0),
        AltitudeToleranceEffect(maximumOptimalAltitudeMeters = 5_500.0, mortalityPerKilometerAbove = 0.20),
    ),
    OPEN_PLAINS_LOCOMOTION(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.006),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 1.05),
        NumericMultiplier(NumericTarget.INTERFERENCE, 0.75),
        HabitatPreferenceEffect(
            axis = HabitatAxis.CANOPY_CLOSURE,
            maximum = 0.25,
            mortalityAtExtreme = 1.10,
        ),
    ),
    WOODLAND_FORAGING(
        RequiresTag(EffectTag.FEEDING),
        MaintenanceCost(0.004),
        NumericMultiplier(NumericTarget.INTERFERENCE, 0.85),
        HabitatRefugeEffect(
            axis = HabitatAxis.CANOPY_CLOSURE,
            refugeStartsAt = 0.10,
            predatorPreferenceAtFullRefuge = 0.65,
        ),
        HabitatPreferenceEffect(
            axis = HabitatAxis.CANOPY_CLOSURE,
            maximum = 0.75,
            mortalityAtExtreme = 0.45,
        ),
    ),
    WETLAND_BREEDING(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.004),
        HabitatPreferenceEffect(
            axis = HabitatAxis.WETLAND_AVAILABILITY,
            minimum = 0.25,
            mortalityAtExtreme = 0.65,
        ),
        HabitatRefugeEffect(
            axis = HabitatAxis.WETLAND_AVAILABILITY,
            refugeStartsAt = 0.20,
            predatorPreferenceAtFullRefuge = 0.50,
        ),
    ),
    AQUATIC_LARVAE(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.006),
        NumericMultiplier(NumericTarget.MORTALITY_RATE, 0.85),
        HabitatRefugeEffect(
            axis = HabitatAxis.WETLAND_AVAILABILITY,
            refugeStartsAt = 0.25,
            predatorPreferenceAtFullRefuge = 0.30,
        ),
    ),
    PERMEABLE_SKIN(
        RequiresTag(EffectTag.MOTILE),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 1.50),
    ),
    PROJECTILE_TONGUE(
        RequiresTag(EffectTag.FEEDING),
        GrantsTag(EffectTag.AERIAL_PREY_CAPTURE),
        MaintenanceCost(0.006),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 1.12),
    ),
    BOG_ROOTS(
        RequiresTag(EffectTag.SESSILE),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 1.50),
    ),
    HUMP_FAT(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.018),
        NumericMultiplier(NumericTarget.STARVATION_MORTALITY_RATE, 0.55),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, 2.0),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 0.55),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, 4.0),
    ),
    RUMINANT_STOMACH(
        RequiresTag(EffectTag.FEEDING),
        MaintenanceCost(0.005),
        FeedsOn(FoodResource.COARSE_GRASS, preference = 1.00),
        NumericMultiplier(NumericTarget.ASSIMILATION_EFFICIENCY, 1.15),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 0.90),
    ),
    HINDGUT_FERMENTATION(
        RequiresTag(EffectTag.FEEDING),
        MaintenanceCost(0.012),
        NumericMultiplier(NumericTarget.ASSIMILATION_EFFICIENCY, 1.10),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 1.05),
    ),
    LONG_NECK(
        RequiresTag(EffectTag.FEEDING),
        MaintenanceCost(0.018),
        FeedsOn(FoodResource.CANOPY_FOLIAGE, preference = 1.15),
    ),
    PREHENSILE_TRUNK(
        RequiresTag(EffectTag.FEEDING),
        MaintenanceCost(0.015),
        FeedsOn(FoodResource.LOW_FOLIAGE, preference = 1.05),
        FeedsOn(FoodResource.CANOPY_FOLIAGE, preference = 1.10),
        FeedsOn(FoodResource.FRUIT, preference = 1.10),
    ),
    TUSKS(
        MaintenanceCost(0.015),
        DefenseEffect(
            defaultPreferenceMultiplier = 0.55,
            ignoredWhenFeederSizeAdvantageAtLeast = 2,
        ),
    ),
    SNOW_CAMOUFLAGE(
        ExclusiveEffect(ExclusiveGroup.CAMOUFLAGE),
        MaintenanceCost(0.008),
        CamouflageEffect(CamouflageHabitat.SNOW),
    ),
    DESERT_CAMOUFLAGE(
        ExclusiveEffect(ExclusiveGroup.CAMOUFLAGE),
        MaintenanceCost(0.008),
        CamouflageEffect(CamouflageHabitat.DESERT),
    ),
    GRASSLAND_CAMOUFLAGE(
        ExclusiveEffect(ExclusiveGroup.CAMOUFLAGE),
        MaintenanceCost(0.008),
        CamouflageEffect(CamouflageHabitat.GRASSLAND),
    ),
    FOREST_CAMOUFLAGE(
        ExclusiveEffect(ExclusiveGroup.CAMOUFLAGE),
        MaintenanceCost(0.008),
        CamouflageEffect(CamouflageHabitat.FOREST),
    ),
    ADAPTIVE_CAMOUFLAGE(
        ExclusiveEffect(ExclusiveGroup.CAMOUFLAGE),
        MaintenanceCost(0.040),
        CamouflageEffect(
            habitat = CamouflageHabitat.ADAPTIVE,
            predatorMultiplierWhenMatched = 1.12,
            preyMultiplierWhenMatched = 0.65,
            predatorMultiplierWhenMismatched = 1.12,
            preyMultiplierWhenMismatched = 0.65,
        ),
    ),
    BRIGHT_MATING_PLUMAGE(
        MaintenanceCost(0.012),
        ConspicuousDisplayEffect(predatorHuntingMultiplier = 0.78, preyVulnerabilityMultiplier = 1.55),
    ),
    EXTRAVAGANT_DISPLAY_PLUMES(
        MaintenanceCost(0.025),
        ConspicuousDisplayEffect(predatorHuntingMultiplier = 0.65, preyVulnerabilityMultiplier = 1.85),
    ),
    SCALES(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.012),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, 2.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, 4.0),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_MOISTURE_MM, 0.80),
        DefenseEffect(defaultPreferenceMultiplier = 0.85),
    ),
    HIBERNATION(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.015),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 0.90),
        NumericMultiplier(NumericTarget.METABOLIC_DEMAND_RATE, 0.40),
        NumericMultiplier(NumericTarget.STARVATION_MORTALITY_RATE, 0.35),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -4.0),
        NumericMultiplier(NumericTarget.CLIMATE_STRESS_SENSITIVITY, 0.85),
    ),
    SEASONAL_MIGRATION(
        RequiresTag(EffectTag.MOTILE),
//        MaintenanceCost(0.035),
//        NumericMultiplier(NumericTarget.CLIMATE_STRESS_SENSITIVITY, 0.65),
    ),
    INSULATING_FEATHERS(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.008),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -6.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, -2.0),
    ),
    STREAMLINED_BODY(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.012),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 1.10),
        NumericMultiplier(NumericTarget.INTERFERENCE, 0.85),
    ),
    GILLS(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.004),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 1.04),
    ),
    SCHOOLING(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.010),
        NumericMultiplier(NumericTarget.INTERFERENCE, 0.80),
        DefenseEffect(
            defaultPreferenceMultiplier = 0.65,
            counterMultipliers = mapOf(EffectTag.CHASE_HUNTING to 0.90),
        ),
    ),
    JET_PROPULSION(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.012),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 1.08),
        NumericMultiplier(NumericTarget.INTERFERENCE, 0.90),
    ),
    ATTACHED_FILTER_FEEDER(
        GrantsTag(EffectTag.SESSILE),
        ConflictsWithTag(EffectTag.MOTILE),
        MaintenanceCost(0.004),
        NumericMultiplier(NumericTarget.INTERFERENCE, 0.75),
    ),
    MARINE_HOLDFAST(
        RequiresTag(EffectTag.SESSILE),
        MaintenanceCost(0.006),
        NumericMultiplier(NumericTarget.CARRYING_CAPACITY, 1.20),
        NumericMultiplier(NumericTarget.AUTOTROPHY_GROWTH_RATE, 0.95),
    ),
    SILICA_FRUSTULE(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.006),
        DefenseEffect(defaultPreferenceMultiplier = 0.78),
    ),
    REEF_BUILDING(
        RequiresTag(EffectTag.AUTOTROPHY),
        RequiresTag(EffectTag.SESSILE),
        MaintenanceCost(0.020),
        NumericMultiplier(NumericTarget.CARRYING_CAPACITY, 1.35),
        NumericMultiplier(NumericTarget.AUTOTROPHY_GROWTH_RATE, 0.55),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, 10.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, 5.0),
    ),
    COLD_WATER_ENZYMES(
        MaintenanceCost(0.010),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -10.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, -4.0),
    ),
    HEAT_SHOCK_PROTEINS(
        MaintenanceCost(0.009),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, 5.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, 7.0),
    ),
    ECHOLOCATION(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.025),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_INSOLATION_W_M2, 0.0),
    ),
    ELECTRORECEPTION(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.018),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_INSOLATION_W_M2, 0.0),
    ),
    BIOLUMINESCENT_LURE(
        RequiresTag(EffectTag.FEEDING),
        MaintenanceCost(0.025),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_INSOLATION_W_M2, 0.0),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 1.10),
    ),
    HEAT_SENSING_PITS(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.012),
        NumericMultiplier(NumericTarget.MIN_OPTIMUM_INSOLATION_W_M2, 0.30),
    ),
    LOW_BASAL_METABOLISM(
        RequiresTag(EffectTag.MOTILE),
        NumericMultiplier(NumericTarget.MAX_CONSUMPTION_RATE, 0.35),
        NumericMultiplier(NumericTarget.MORTALITY_RATE, 0.35),
        NumericMultiplier(NumericTarget.METABOLIC_DEMAND_RATE, 0.35),
        NumericMultiplier(NumericTarget.STARVATION_MORTALITY_RATE, 0.50),
    ),
    ANTIFREEZE_PROTEINS(
        RequiresTag(EffectTag.MOTILE),
        MaintenanceCost(0.015),
        NumericOffset(NumericTarget.MIN_OPTIMUM_TEMPERATURE_C, -6.0),
        NumericOffset(NumericTarget.MAX_OPTIMUM_TEMPERATURE_C, -1.0),
    ),
    WATERLOGGING_SENSITIVE_ROOTS(
        RequiresTag(EffectTag.SESSILE),
        NumericUpperBound(NumericTarget.MAX_OPTIMUM_MOISTURE_MM, 120.0),
    );

    /** Immutable effects declared by this named trait. */
    override val effects: List<TraitEffect> = effectList.toList()
}
